### ISSUE TITLE
Name for actions

### ISSUE THREAD

**Issue by egorsmkv** [udokmeci/yii2-beanstalk#26]
Please add the conversion action games titles.

```php
public function listenTubes()
    {
        return ['signup_verify'];
    }
```

```php
public function actionSignupVerify($job)
```

It is an error:

```bash
/s/http — php ./yii worker
Process Control Extension is loaded. Signal Handling Registered!
Not Listening default tube since there is no action defined. actionDefault
Not Listening signup_verify tube since there is no action defined. actionSignup_verify
No tube found to listen!
```

**Comment by udokmeci** [comment]
Hi,

I can not confirm directly now since weerkend but i would be similar to yii's action name convention which would signup-verify.

Can use please try and let me know

Bests

5 Haziran 2016 13:44:23 GMT+03:00, Egor Smolyakov <notifications@github.com> yazdı:
>Please add the conversion action games titles.
>
>```php
>public function listenTubes()
>    {
>        return ['signup_verify'];
>    }
>```
>
>```php
>public function actionSignupVerify($job)
>```
>
>It is an error:
>
>```bash
>/s/http — php ./yii worker
>Process Control Extension is loaded. Signal Handling Registered!
>Not Listening default tube since there is no action defined.
>actionDefault
>Not Listening signup_verify tube since there is no action defined.
>actionSignup_verify
>No tube found to listen!
>```
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/udokmeci/yii2-beanstalk/issues/26

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by egorsmkv** [comment]
Oh thanks! That was my fault.
